---
- block:
    - name: include preflight
      include_tasks: preflight.yml
      tags:
        - blackbox_exporter_install
        - blackbox_exporter_configure
        - blackbox_exporter_run

    - name: include install
      include_tasks: install.yml
      tags:
        - blackbox_exporter_install

    - name: include configure
      include_tasks: configure.yml
      tags:
        - blackbox_exporter_configure
  become: true
- name: ensure blackbox_exporter service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: started
    enabled: true
  tags:
    - blackbox_exporter_run
